#include "ffb.h"
#include <string.h>

#define LG_COMMAND_MASK 0x0fu
#define LG_SLOT_MASK 0xf0u
#define LG_DOWNLOAD 0x00u
#define LG_DOWNLOAD_AND_PLAY 0x01u
#define LG_REFRESH 0x0cu
#define LG_CONSTANT_FORCE 0x00u
#define LG_VARIABLE_FORCE 0x08u

// y = x^0.65, sampled at the 127 usable magnitudes in Logitech's classic
// protocol. Keeping this as bytes avoids floating point in the USB path.
static const uint8_t progressive_lut[128] = {
    0, 5, 9, 11, 13, 16, 17, 19, 21, 23, 24, 26, 27, 29, 30, 32,
    33, 34, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 48, 49, 50, 51,
    52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
    67, 68, 69, 70, 71, 72, 73, 74, 75, 75, 76, 77, 78, 79, 80, 81,
    81, 82, 83, 84, 85, 85, 86, 87, 88, 89, 89, 90, 91, 92, 93, 93,
    94, 95, 96, 96, 97, 98, 99, 99, 100, 101, 102, 102, 103, 104, 104, 105,
    106, 107, 107, 108, 109, 109, 110, 111, 112, 112, 113, 114, 114, 115, 116, 116,
    117, 118, 118, 119, 120, 120, 121, 122, 122, 123, 124, 124, 125, 126, 126, 127
};

// Linear interpolation of profiles/g27-measured.lut at x = magnitude / 127,
// quantized to the classic protocol's 127 positive magnitudes.
static const uint8_t g27_measured_lut[128] = {
    0, 16, 21, 21, 21, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26,
    26, 26, 26, 27, 27, 28, 28, 29, 30, 30, 31, 32, 32, 33, 33, 34,
    34, 35, 35, 35, 35, 35, 36, 36, 36, 37, 38, 38, 39, 39, 39, 40,
    40, 40, 40, 41, 42, 42, 42, 43, 43, 43, 44, 44, 45, 45, 45, 46,
    46, 46, 47, 47, 48, 50, 51, 52, 54, 56, 57, 58, 60, 62, 64, 65,
    67, 70, 71, 72, 74, 77, 79, 81, 82, 82, 82, 86, 89, 90, 91, 94,
    95, 95, 97, 99, 100, 100, 101, 102, 104, 105, 106, 107, 108, 110, 111, 111,
    111, 111, 111, 111, 111, 112, 112, 112, 114, 117, 118, 121, 124, 125, 126, 127
};

static uint8_t minimum_force(uint8_t magnitude, uint8_t minimum) {
    if (!magnitude) return 0;
    // Map 1..127 to minimum..127, retaining full-scale output without clipping.
    return (uint8_t) (minimum +
        ((uint16_t) (127u - minimum) * (magnitude - 1u) + 63u) / 126u);
}

static uint8_t transform_level(ffb_profile_t profile, uint8_t level) {
    // Logitech treats both 127 and 128 as center. Preserve both exactly.
    if (level == 127u || level == 128u || profile == FFB_PROFILE_LINEAR) return level;

    bool negative = level < 127u;
    uint8_t magnitude = negative ? (uint8_t) (127u - level) : (uint8_t) (level - 128u);
    switch (profile) {
        case FFB_PROFILE_MINIMUM_12: magnitude = minimum_force(magnitude, 15u); break;
        case FFB_PROFILE_MINIMUM_18: magnitude = minimum_force(magnitude, 23u); break;
        case FFB_PROFILE_PROGRESSIVE: magnitude = progressive_lut[magnitude]; break;
        case FFB_PROFILE_G27_MEASURED: magnitude = g27_measured_lut[magnitude]; break;
        default: return level;
    }
    return negative ? (uint8_t) (127u - magnitude) : (uint8_t) (128u + magnitude);
}

static bool transform_torque_force(ffb_queue_t* queue, uint8_t command[FFB_COMMAND_SIZE]) {
    uint8_t operation = command[0] & LG_COMMAND_MASK;
    if (!queue->profiles_enabled || queue->profile == FFB_PROFILE_LINEAR ||
        (operation != LG_DOWNLOAD && operation != LG_DOWNLOAD_AND_PLAY && operation != LG_REFRESH)) {
        return false;
    }

    bool changed = false;
    if (command[1] == LG_CONSTANT_FORCE) {
        uint8_t slots = command[0] & LG_SLOT_MASK;
        for (unsigned slot = 0; slot < 4; slot++) {
            if (!(slots & (0x10u << slot))) continue;
            uint8_t transformed = transform_level(queue->profile, command[2u + slot]);
            changed |= transformed != command[2u + slot];
            command[2u + slot] = transformed;
        }
    } else if (command[1] == LG_VARIABLE_FORCE && command[4] == 0 && command[5] == 0) {
        // Linux and the adapter's bench test express steady torque as a
        // variable force with two initial levels and zero time/step nibbles.
        // Leave actual ramps untouched because their later samples are
        // generated by the wheel and cannot be curved here.
        uint8_t slots = command[0] & LG_SLOT_MASK;
        if (slots & 0x10u) {
            uint8_t transformed = transform_level(queue->profile, command[2]);
            changed |= transformed != command[2];
            command[2] = transformed;
        }
        if (slots & 0x40u) {
            uint8_t transformed = transform_level(queue->profile, command[3]);
            changed |= transformed != command[3];
            command[3] = transformed;
        }
    }
    return changed;
}

bool ffb_enqueue_report(ffb_queue_t* queue, uint8_t report_id, const uint8_t* data, size_t length) {
    if (!data) { queue->invalid++; return false; }
    if (report_id == 0 && length && data[0] == 5) {
        data++; length--; report_id = 5;
    }
    // The PS5 uses the legacy shape handled by the upstream adapter: metadata
    // does not identify report 5, while byte 0 precedes the seven-byte Logitech
    // command. Keep strict report-5 handling first, then use that proven layout.
    if (report_id != 5 && length > FFB_COMMAND_SIZE) {
        data++; length--; report_id = 5;
    }
    if (report_id != 5 || length < FFB_COMMAND_SIZE) {
        queue->invalid++;
        return false;
    }
    // Identity changes belong to our host-side initialization, not to the PS5.
    // Forward ranges, RPM LEDs, spring/damper setup and force samples unchanged.
    if (data[0] == 0xf8 && (data[1] == 0x01 || data[1] == 0x09 ||
        data[1] == 0x0a || data[1] == 0x10 || data[1] == 0x11)) {
        queue->blocked_mode_changes++;
        return false;
    }
    queue->received++;
    if (queue->count == FFB_QUEUE_CAPACITY) {
        queue->overflows++;
        return false;
    }
    uint8_t* command = queue->commands[(queue->head + queue->count) % FFB_QUEUE_CAPACITY];
    memcpy(command, data, FFB_COMMAND_SIZE);
    if (transform_torque_force(queue, command)) queue->transformed++;
    queue->count++;
    if (queue->count > queue->high_water) queue->high_water = queue->count;
    return true;
}

const uint8_t* ffb_front(const ffb_queue_t* queue) {
    return queue->count ? queue->commands[queue->head] : NULL;
}

void ffb_pop(ffb_queue_t* queue) {
    if (!queue->count) return;
    queue->head = (queue->head + 1u) % FFB_QUEUE_CAPACITY;
    queue->count--;
    queue->sent++;
}

bool ffb_command_is_rpm_led(const uint8_t* command) {
    return command && command[0] == 0xf8u && command[1] == 0x12u;
}

void ffb_suppress_front_led(ffb_queue_t* queue) {
    if (!queue || !queue->count || !ffb_command_is_rpm_led(queue->commands[queue->head])) return;
    queue->head = (queue->head + 1u) % FFB_QUEUE_CAPACITY;
    queue->count--;
    queue->suppressed_leds++;
}

void ffb_clear(ffb_queue_t* queue) {
    queue->head = 0;
    queue->count = 0;
}

bool ffb_profile_valid(uint8_t profile) {
    return profile < FFB_PROFILE_COUNT;
}

void ffb_set_profile(ffb_queue_t* queue, ffb_profile_t profile) {
    if (queue && ffb_profile_valid((uint8_t) profile)) queue->profile = profile;
}

void ffb_enable_profiles(ffb_queue_t* queue, bool enabled) {
    if (queue) queue->profiles_enabled = enabled;
}

ffb_profile_t ffb_next_profile(ffb_profile_t profile) {
    return ffb_profile_valid((uint8_t) profile) ?
        (ffb_profile_t) ((profile + 1u) % FFB_PROFILE_COUNT) : FFB_PROFILE_MINIMUM_12;
}

const char* ffb_profile_name(ffb_profile_t profile) {
    static const char* const names[FFB_PROFILE_COUNT] = {
        "Linear", "Minimum force 12%", "Minimum force 18%", "Progressive", "G27 measured LUT"
    };
    return ffb_profile_valid((uint8_t) profile) ? names[profile] : "Invalid";
}
